### ISSUE TITLE
"missing arguments for method project" executing task

### ISSUE THREAD

**Issue by dustinsand** [Fabszn/scaffolding-plugin-lagom#7]
Followed the instructions to add the plugin in plugins.sbt and build.sbt, but I'm getting this error.  What step was missed?

error: missing arguments for method project in object $e2bfb6f9285e7d3e851b;
follow this method with `_' if you want to treat it as a partially applied function
lazy val root = (project in file("."))
                 ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by Fabszn** [comment]
Hi,

Many thanks for your feed-back. 
Could you please post here the content of your build.sbt file?

**Comment by dustinsand** [comment]
Hi Fabrice,

plugins.sbt:

// The Lagom plugin
addSbtPlugin("com.lightbend.lagom" % "lagom-sbt-plugin" % "1.0.0")
// The ConductR plugin
addSbtPlugin("com.lightbend.conductr" % "sbt-conductr" % "2.1.4")

// The Scaffolding-plugin for Lagom (https://github.com/Fabszn/scaffolding-plugin-lagom)
resolvers += Resolver.url("bintray.scaffolding-plugin.resolver", url("http://dl.bintray.com/fabszn/sbt-plugins"))(Resolver.ivyStylePatterns)
addSbtPlugin("com.lightbend.lagom.sbt" %% "scaffolding-plugin-lagom" % "1.0.0-M1")

build.sbt:

import sbt._

organization in ThisBuild := "com.acme"

// the Scala version that will be used for cross-compiled libraries
scalaVersion in ThisBuild := "2.11.7"

// The Scaffolding-plugin for Lagom (https://github.com/Fabszn/scaffolding-plugin-lagom)
lazy val root = (project in file("."))
    .enablePlugins(LagomScaffoldingPlugin)

Do you need the entire contents of build.sbt?  The remaining was standard for an activator created build.sbt.

Thanks,
Dustin

**Comment by Fabszn** [comment]
Thanks for those informations.
I forgot to ask you the version of sbt that you are using.
Thanks

**Comment by dustinsand** [comment]
sbt 0.13.11

**Comment by Fabszn** [comment]
Hello Dustin,

Sorry for the delay of my answer, I am actually in vacation and I have got one very bad internet connexion.

Well, I understood what happend with your project.
I understand well, you have an initial lagom project that has been generated by the  lagom activator template. 

The activator adds a method close to the end of your build.sbt file with the following signature : 

``` scala
def project(id: String) = Project(id, base = file(id))
  .settings(eclipseSettings: _*)
  .settings(javacOptions in compile ++= Seq("-encoding", "UTF-8", "-source", "1.8", "-target", "1.8", "-Xlint:unchecked", "-Xlint:deprecation"))
  .settings(jacksonParameterNamesJavacSettings: _*) // applying it to every project even if not strictly needed.
```

This is a method helper to add some configurations on each services. 

The plugin **scaffolding-plugin-lagom** must be add on the global project (not on a service directly) so it must be enable on the root project.

There is two ways to get around this issue : 

1) replace the code in the documentation by the following code : 

``` scala
lazy val root = Project("root",base= file("."))
.enablePlugins(LagomScaffoldingPlugin)
```

This allow the creation of the root project and enable the plugin. 
However, you will be faced to same issue, with the generated services by the plugin. 
Apply the same strategy with  

``` Scala
Project(id, base = file("id")) //where id is the name of the service.
```

2) remove the project method from the build.sbt. 
In this way, all existing service will be in error, then just replace the call method : 

``` scala
project(idProject)
```

by

``` scala
(project in file(idProject))
```

and everything should be ok.

The plugin has been created to start project from scratch, not after the generated activator model.

I will update the documentation with this point. 

Let me know if your problem is fixed or not. 
Feel free to ask me any questions.

Regards,

Fabrice

**Comment by dustinsand** [comment]
Fabrice,

Aside, in the README, suggest removing 'dl.' from the URL used for 'The plugin is available on the following repository' so a page is displayed to view the available versions.  If 'dl.' is in the URL, the page contains just an unhelpful link.

I'm not totally clear on what you meant in step 2.  I'll try again once you have had time to update the README as you noted.

I really appreciate you taking the time to respond, however, this can wait until after your vacation!

Regards,
Dustin

**Comment by Fabszn** [comment]
Hi @dustinsand 

URL is fixed, thank you.

I will update documentation soon, my holidays is finished :'( ;)

Regards

**Comment by Fabszn** [comment]
Hi @dustinsand 

How are you?
I updated the documentation and add a new parameter that take in charge both case with and without template activator. 

This is not already released but available on the snapShot version. 
I hope to publish a new version before the end of week end.

I close this issue. If you find some problem, please, feel free to create new one.

Best regards

Fabrice
